plugins {
    id 'com.android.application' version '8.5.0'
}

android {
    namespace 'com.duweim.prayerduweim'
    compileSdk 29

    defaultConfig {
        applicationId "com.duweim.prayerduweim"
        minSdk 21
        targetSdk 29
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
